package fr.ses10doigts.webApp2.model;

public enum TypeCeremonie {

    TEMAZCAL, TAMBOUR1, TAMBOUR2, TAMBOUR3, MINERAUX, ROME, CHANT, PREPA_INTENTIONS, GRANDMERE, PRINCESSE, NINOS,
    HOMMAGE, GRENOUILLE1, GRENOUILLE2, GRENOUILLE3, LIEU, REPAS_DEJ, REPAS;
}
